version: "3.7"

services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=homestead
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgresql-data:/var/lib/postgresql/data/

  # django:
  #   build:
  #     context: ./django
  #     dockerfile: docker/Dockerfile
  #   container_name: django
  #   volumes:
  #     - ./django:/app/django
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DEBUG=false
  #     - DATABASE_NAME=homestead
  #     - DATABASE_USER=homestead
  #     - DATABASE_PASSWORD=secret
  #     - DATABASE_HOST=db
  #     - DATABASE_PORT=5432
  #     - VIRTUAL_HOST=django.localhost
  #   depends_on:
  #     - db

  laravel:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./laravel
      dockerfile: docker/Dockerfile.prod
    container_name: laravel
    environment:
      DB_CONNECTION: pgsql
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 5432
      VIRTUAL_HOST: laravel.localhost
    ports:
      - 8001:8000
    # restart: unless-stopped
    volumes:
      - ./laravel:/app/laravel
    depends_on:
      - db
    networks:
      - app

  # reactjs:
  #   build:
  #     context: ./reactjs
  #     dockerfile: docker/Dockerfile.prod
  #     args:
  #       - API_URL=http://django.localhost/api
  #   container_name: reactjs
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - VIRTUAL_HOST=localhost
  #   volumes:
  #     - ./reactjs:/app/reactjs/:cached
  #   ports:
  #     - 3000:80
  #   depends_on:
  #     - django

  vuejs:
    build:
      context: ./vuejs
      dockerfile: docker/Dockerfile.prod
      args:
        - API_URL=http://laravel.localhost/api
    container_name: vuejs
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VIRTUAL_HOST=vue.localhost
    volumes:
      - ./vuejs:/app/vuejs/:cached
    ports:
      - 8080:80
    restart: always
    depends_on:
      - laravel
    networks:
      - app

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=homestead
  #     - PGADMIN_DEFAULT_PASSWORD=secret
  #     - VIRTUAL_HOST=pgadmin.localhost
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   ports:
  #     - 8002:80

  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    depends_on:
      - laravel
      - vuejs

volumes:
  postgresql-data:
  # pgadmin-data:
networks:
  app:
    driver: bridge
